var rastaurant = [
  {
    name: "The Ora Cafe",
    cat: "North Indian, Beverages",
    rating: "4.0",
    time: "",
    avgPrice: "",
    image: "",
    address: "",
  },
  {
    name: "Mirchi Restaurant",
    cat: "North Indian",
    rating: "3.9",
    time: "20 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Hot Pizza",
    cat: "Italian, Pizzas",
    rating: "3.9",
    time: "23 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Bholenath Pizza Centre",
    cat: "Fast Food, Pizzas",
    rating: "4.2",
    time: "",
    avgPrice: "",
    image: "",
    address: "",
  },
  {
    name: "Kanha ji daal bati",
    cat: "Indian",
    rating: "4.2",
    time: "26 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Asha Restaurant",
    cat: "North Indian, South Indian, Chinese, Snacks",
    rating: "--",
    time: "22 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Eating Seating",
    cat: "Fast Food",
    rating: "3.9",
    time: "",
    avgPrice: "",
    image: "",
    address: "",
  },
  {
    name: "Mahalaxmi Bakers",
    cat: "North Indian, Desserts",
    rating: "4.0",
    time: "17 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Sonu Patties",
    cat: "American, Fast Food, Pizzas, Snacks, Beverages",
    rating: "3.6",
    time: "21 MINS",
    avgPrice: "₹149 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Hangout",
    cat: "Chinese, South Indian, North Indian, Continental, Fast Food",
    rating: "3.7",
    time: "20 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Angeethi Restaurant (Hotel Ashoka Residency)",
    cat: "Desserts, Thai",
    rating: "3.1",
    time: "24 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Mateshwari Falhari Center",
    cat: "Snacks, Fast Food",
    rating: "--",
    time: "18 MINS",
    avgPrice: "₹100 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Hotel Raza",
    cat: "Mughlai",
    rating: "3.2",
    time: "20 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Bikaner Family Restaurant",
    cat: "North Indian",
    rating: "3.2",
    time: "23 MINS",
    avgPrice: "₹220 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "City Hart momos",
    cat: "Snacks, Fast Food",
    rating: "--",
    time: "29 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "INOX",
    cat: "Fast Food",
    rating: "--",
    time: "24 MINS",
    avgPrice: "₹400 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "SM Maggi n pasta",
    cat: "Fast Food, Pastas",
    rating: "--",
    time: "23 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Jodhpur Sweets",
    cat: "Desserts, Snacks",
    rating: "4.1",
    time: "16 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Chalta Firta Restaurant",
    cat: "North Indian, Rajasthani",
    rating: "--",
    time: "31 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "SS Chowmein & Manchurian",
    cat: "North Indian",
    rating: "3.6",
    time: "22 MINS",
    avgPrice: "₹100 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Chawla Chicken",
    cat: "Mughlai, Punjabi",
    rating: "3.3",
    time: "24 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Baskin Robbins",
    cat: "Desserts",
    rating: "4.0",
    time: "20 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Saffron The Family Restaurant",
    cat: "North Indian",
    rating: "3.5",
    time: "21 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Aloo Bada Centre",
    cat: "Snacks",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹50 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Bikaner Bhojnalaya",
    cat: "North Indian",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "O-zone Cafe",
    cat: "Pizzas, Fast Food, Snacks, Chinese, Beverages",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹100 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Suruchi Restaurant",
    cat: "North Indian",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Crave Nation",
    cat: "North Indian",
    rating: "--",
    time: "22 MINS",
    avgPrice: "₹350 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "The Brij Kanha restaurant",
    cat: "Indian",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹500 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "The Roll Junction",
    cat: "Fast Food, Mexican, North Indian",
    rating: "3.3",
    time: "26 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "The Brown Sugar Bakery",
    cat: "Desserts, Bakery",
    rating: "4.4",
    time: "25 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Delhi Thali Restaurant",
    cat: "North Indian, Desserts",
    rating: "3.7",
    time: "19 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Hotel Apsara",
    cat: "North Indian",
    rating: "3.2",
    time: "24 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Shree Sanwariya Restaurant",
    cat: "North Indian, Rajasthani",
    rating: "4.2",
    time: "27 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Score board sports cafe",
    cat: "Fast Food, Italian, North Indian, Pizzas",
    rating: "3.1",
    time: "25 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Mami ka pizza",
    cat: "Indian",
    rating: "3.0",
    time: "25 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Apsara patties and pizza",
    cat: "Pizzas, Fast Food, Beverages",
    rating: "--",
    time: "24 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Harichhaya Garden restaurant",
    cat: "North Indian",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Roll express",
    cat: "North Indian, Chinese, Snacks",
    rating: "4.1",
    time: "27 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Gourmet Ice Cream Cakes by Baskin Robbins",
    cat: "Desserts, Ice Cream, Bakery",
    rating: "--",
    time: "29 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Bobbys cafe",
    cat: "Fast Food",
    rating: "--",
    time: "26 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Eva s Eatery",
    cat: "Fast Food, Beverages",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "SN Pizza",
    cat: "North Indian",
    rating: "--",
    time: "31 MINS",
    avgPrice: "₹150 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "The Storix cafe",
    cat: "Italian, Continental, Beverages",
    rating: "--",
    time: "30 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "TEA & TALKS",
    cat: "Beverages, Snacks, Pizzas",
    rating: "--",
    time: "26 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Shree Sanwariya Bhojnalaya",
    cat: "Indian, Rajasthani",
    rating: "--",
    time: "34 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Sip & Gossip Cafe",
    cat: "North Indian",
    rating: "3.9",
    time: "31 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Ministry of Pastry Bakehouse",
    cat: "Bakery, Desserts, Snacks, Beverages",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Hotel Tulip continental",
    cat: "Chinese, South Indian, North Indian, Continental, American, Desserts, Fast Food,...",
    rating: "--",
    time: "31 MINS",
    avgPrice: "₹500 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "The Mojo Cake N Bake",
    cat: "Fast Food, Chinese, Beverages",
    rating: "--",
    time: "33 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Coffee Culture",
    cat: "Pizzas, Pastas, Italian, Indian, American, Chinese, Fast Food, Mexican, Beverage...",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹350 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Blue Umbrella Bakers",
    cat: "Bakery, Desserts",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹400 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Hari Sewa Bakers",
    cat: "Bakery",
    rating: "--",
    time: "33 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Surprise India",
    cat: "Bakery",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Shreenath Pav Bahji",
    cat: "North Indian, Fast Food",
    rating: "--",
    time: "24 MINS",
    avgPrice: "₹100 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Balaji Fast Food",
    cat: "Fast Food",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹150 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Domino's Pizza",
    cat: "Pizzas",
    rating: "3.5",
    time: "30 MINS",
    avgPrice: "₹400 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Sukhwal Fast Food",
    cat: "Fast Food",
    rating: "3.6",
    time: "25 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Seven Stone",
    cat: "Continental, Fast Food, North Indian",
    rating: "--",
    time: "34 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Dev Restaurant",
    cat: "North Indian",
    rating: "3.6",
    time: "30 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Street Wok",
    cat: "Fast Food",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Love bird pizza",
    cat: "Continental",
    rating: "4.0",
    time: "25 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Shree Ram Pizza Corner",
    cat: "Ice Cream, Desserts",
    rating: "--",
    time: "34 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Chef's secret...",
    cat: "Indian, Chinese, Beverages",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹150 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Chicken Point",
    cat: "Indian, Biryani, Beverages",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹220 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Rasoda",
    cat: "North Indian, Chinese, Snacks",
    rating: "4.1",
    time: "28 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "H3 Cafe - By Dosa Planet",
    cat: "South Indian, Beverages",
    rating: "3.5",
    time: "29 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Curry by kilo by Ora Foods",
    cat: "North Indian, Snacks, Beverages",
    rating: "--",
    time: "28 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Pink plate",
    cat: "Indian, Continental, Beverages",
    rating: "--",
    time: "33 MINS",
    avgPrice: "₹350 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "SM Maggi",
    cat: "North Indian",
    rating: "--",
    time: "26 MINS",
    avgPrice: "₹100 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Radhey Kachori Center",
    cat: "North Indian, Sweets, Snacks",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Hotel Radiance",
    cat: "North Indian, Chinese, Pizzas",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "303 The Royal Recipes",
    cat: "South Indian, Indian, Beverages",
    rating: "--",
    time: "29 MINS",
    avgPrice: "₹600 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Lovish cake n bake",
    cat: "Bakery",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹400 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Mateshwari falhari",
    cat: "North Indian",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹100 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Chetna Pizza",
    cat: "Pizzas, Fast Food",
    rating: "--",
    time: "35 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Fumes & Flames",
    cat: "North Indian",
    rating: "--",
    time: "26 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Salty house",
    cat: "North Indian, Fast Food",
    rating: "--",
    time: "28 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "House of masala",
    cat: "Oriental, Continental",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹350 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Masala nonveg restaurant",
    cat: "Indian",
    rating: "--",
    time: "30 MINS",
    avgPrice: "₹350 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "B12 Garden Restaurant",
    cat: "North Indian",
    rating: "--",
    time: "29 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Cam`s Kitchen",
    cat: "Indian",
    rating: "--",
    time: "30 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "THE CHAWLA'S BAKERY",
    cat: "Bakery, Fast Food, Pizzas, Desserts, Beverages",
    rating: "--",
    time: "24 MINS",
    avgPrice: "₹300 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Firangi Club",
    cat: "Continental, North Indian",
    rating: "--",
    time: "31 MINS",
    avgPrice: "₹400 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "OM SHREE SAI KRIPA",
    cat: "Chinese, Indian, Juices",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹200 FOR TWO",
    image: "",
    address: "",
  },
  {
    name: "Tikka N Talk",
    cat: "North Indian",
    rating: "--",
    time: "39 MINS",
    avgPrice: "₹250 FOR TWO",
    image: "",
    address: "",
  },
];
