export const RestaurantData = [
  {
    title: "The Ora Cafe",
    categories: "North Indian, Beverages",
    rating: "4.0",
    time: "25 mins",
    avgPrice: "₹ 200 Cost for two",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/sdvbpv9nvx4xzoujrwql",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Sanjay Colony",
  },
  {
    title: "Mirchi Restaurant",
    categories: "North Indian",
    rating: "3.9",
    time: "20 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/povypukzcottzmhmy4fy",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Hot Pizza",
    categories: "Italian, Pizzas",
    rating: "3.9",
    time: "23 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/onrussybboydf7hpidkr",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Bholenath Pizza Centre",
    categories: "Fast Food, Pizzas",
    rating: "4.2",
    time: "",
    avgPrice: "",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Kanha ji daal bati",
    categories: "Indian",
    rating: "4.2",
    time: "26 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Asha Restaurant",
    categories: "North Indian, South Indian, Chinese, Snacks",
    rating: "--",
    time: "22 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/vczeztxo1wpk9pqxiucq",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Old Bhilwara, Shastri Nagar",
  },
  {
    title: "Eating Seating",
    categories: "Fast Food",
    rating: "3.9",
    time: "",
    avgPrice: "",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Mahalaxmi Bakers",
    categories: "North Indian, Desserts",
    rating: "4.0",
    time: "17 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Sonu Patties",
    categories: "American, Fast Food, Pizzas, Snacks, Beverages",
    rating: "3.6",
    time: "21 MINS",
    avgPrice: "₹149 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Hangout",
    categories: "Chinese, South Indian, North Indian, Continental, Fast Food",
    rating: "3.7",
    time: "20 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Angeethi Restaurant (Hotel Ashoka Residency)",
    categories: "Desserts, Thai",
    rating: "3.1",
    time: "24 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/vejmtuy9txuwelm0xeba",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Shastri Nagar",
  },
  {
    title: "Mateshwari Falhari Center",
    categories: "Snacks, Fast Food",
    rating: "--",
    time: "18 MINS",
    avgPrice: "₹100 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Hotel Raza",
    categories: "Mughlai",
    rating: "3.2",
    time: "20 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Bikaner Family Restaurant",
    categories: "North Indian",
    rating: "3.2",
    time: "23 MINS",
    avgPrice: "₹220 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "City Hart momos",
    categories: "Snacks, Fast Food",
    rating: "--",
    time: "29 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "INOX",
    categories: "Fast Food",
    rating: "--",
    time: "24 MINS",
    avgPrice: "₹400 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "SM Maggi n pasta",
    categories: "Fast Food, Pastas",
    rating: "--",
    time: "23 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Jodhpur Sweets",
    categories: "Desserts, Snacks",
    rating: "4.1",
    time: "16 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Chalta Firta Restaurant",
    categories: "North Indian, Rajasthani",
    rating: "--",
    time: "31 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/xg0vcdztyvdxjbxkswsf",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Old Bhilwara, Shastri Nagar",
  },
  {
    title: "SS Chowmein & Manchurian",
    categories: "North Indian",
    rating: "3.6",
    time: "22 MINS",
    avgPrice: "₹100 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Chawla Chicken",
    categories: "Mughlai, Punjabi",
    rating: "3.3",
    time: "24 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Baskin Robbins",
    categories: "Desserts",
    rating: "4.0",
    time: "20 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Saffron The Family Restaurant",
    categories: "North Indian",
    rating: "3.5",
    time: "21 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Aloo Bada Centre",
    categories: "Snacks",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹50 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Bikaner Bhojnalaya",
    categories: "North Indian",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "O-zone Cafe",
    categories: "Pizzas, Fast Food, Snacks, Chinese, Beverages",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹100 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Suruchi Restaurant",
    categories: "North Indian",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Crave Nation",
    categories: "North Indian",
    rating: "--",
    time: "22 MINS",
    avgPrice: "₹350 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "The Brij Kanha restaurant",
    categories: "Indian",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹500 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "The Roll Junction",
    categories: "Fast Food, Mexican, North Indian",
    rating: "3.3",
    time: "26 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "The Brown Sugar Bakery",
    categories: "Desserts, Bakery",
    rating: "4.4",
    time: "25 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Delhi Thali Restaurant",
    categories: "North Indian, Desserts",
    rating: "3.7",
    time: "19 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Hotel Apsara",
    categories: "North Indian",
    rating: "3.2",
    time: "24 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Shree Sanwariya Restaurant",
    categories: "North Indian, Rajasthani",
    rating: "4.2",
    time: "27 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url:
      "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/akbnfuabaonpdvrmagcb",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Old Bhilwara, Azad Nagar",
  },
  {
    title: "Score board sports cafe",
    categories: "Fast Food, Italian, North Indian, Pizzas",
    rating: "3.1",
    time: "25 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "Bhilwara, Bhopal Ganj",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Mami ka pizza",
    categories: "Indian",
    rating: "3.0",
    time: "25 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Apsara patties and pizza",
    categories: "Pizzas, Fast Food, Beverages",
    rating: "--",
    time: "24 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Harichhaya Garden restaurant",
    categories: "North Indian",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Roll express",
    categories: "North Indian, Chinese, Snacks",
    rating: "4.1",
    time: "27 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Gourmet Ice Cream Cakes by Baskin Robbins",
    categories: "Desserts, Ice Cream, Bakery",
    rating: "--",
    time: "29 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Bobbys cafe",
    categories: "Fast Food",
    rating: "--",
    time: "26 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Eva s Eatery",
    categories: "Fast Food, Beverages",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "SN Pizza",
    categories: "North Indian",
    rating: "--",
    time: "31 MINS",
    avgPrice: "₹150 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "The Storix cafe",
    categories: "Italian, Continental, Beverages",
    rating: "--",
    time: "30 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "TEA & TALKS",
    categories: "Beverages, Snacks, Pizzas",
    rating: "--",
    time: "26 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Shree Sanwariya Bhojnalaya",
    categories: "Indian, Rajasthani",
    rating: "--",
    time: "34 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Sip & Gossip Cafe",
    categories: "North Indian",
    rating: "3.9",
    time: "31 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Ministry of Pastry Bakehouse",
    categories: "Bakery, Desserts, Snacks, Beverages",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Hotel Tulip continental",
    categories: "Chinese, South Indian, North Indian, Continental, American, Desserts, Fast Food,...",
    rating: "--",
    time: "31 MINS",
    avgPrice: "₹500 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "The Mojo Cake N Bake",
    categories: "Fast Food, Chinese, Beverages",
    rating: "--",
    time: "33 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Coffee Culture",
    categories: "Pizzas, Pastas, Italian, Indian, American, Chinese, Fast Food, Mexican, Beverage...",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹350 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Blue Umbrella Bakers",
    categories: "Bakery, Desserts",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹400 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Hari Sewa Bakers",
    categories: "Bakery",
    rating: "--",
    time: "33 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Surprise India",
    categories: "Bakery",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Shreenath Pav Bahji",
    categories: "North Indian, Fast Food",
    rating: "--",
    time: "24 MINS",
    avgPrice: "₹100 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Balaji Fast Food",
    categories: "Fast Food",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹150 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Domino's Pizza",
    categories: "Pizzas",
    rating: "3.5",
    time: "30 MINS",
    avgPrice: "₹400 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Sukhwal Fast Food",
    categories: "Fast Food",
    rating: "3.6",
    time: "25 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Seven Stone",
    categories: "Continental, Fast Food, North Indian",
    rating: "--",
    time: "34 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Dev Restaurant",
    categories: "North Indian",
    rating: "3.6",
    time: "30 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Street Wok",
    categories: "Fast Food",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Love bird pizza",
    categories: "Continental",
    rating: "4.0",
    time: "25 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Shree Ram Pizza Corner",
    categories: "Ice Cream, Desserts",
    rating: "--",
    time: "34 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Chef's secret...",
    categories: "Indian, Chinese, Beverages",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹150 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Chicken Point",
    categories: "Indian, Biryani, Beverages",
    rating: "--",
    time: "27 MINS",
    avgPrice: "₹220 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Rasoda",
    categories: "North Indian, Chinese, Snacks",
    rating: "4.1",
    time: "28 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "H3 Cafe - By Dosa Planet",
    categories: "South Indian, Beverages",
    rating: "3.5",
    time: "29 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Curry by kilo by Ora Foods",
    categories: "North Indian, Snacks, Beverages",
    rating: "--",
    time: "28 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Pink plate",
    categories: "Indian, Continental, Beverages",
    rating: "--",
    time: "33 MINS",
    avgPrice: "₹350 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "SM Maggi",
    categories: "North Indian",
    rating: "--",
    time: "26 MINS",
    avgPrice: "₹100 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Radhey Kachori Center",
    categories: "North Indian, Sweets, Snacks",
    rating: "--",
    time: "25 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Hotel Radiance",
    categories: "North Indian, Chinese, Pizzas",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "303 The Royal Recipes",
    categories: "South Indian, Indian, Beverages",
    rating: "--",
    time: "29 MINS",
    avgPrice: "₹600 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Lovish cake n bake",
    categories: "Bakery",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹400 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Mateshwari falhari",
    categories: "North Indian",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹100 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Chetna Pizza",
    categories: "Pizzas, Fast Food",
    rating: "--",
    time: "35 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Fumes & Flames",
    categories: "North Indian",
    rating: "--",
    time: "26 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Salty house",
    categories: "North Indian, Fast Food",
    rating: "--",
    time: "28 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "House of masala",
    categories: "Oriental, Continental",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹350 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
  {
    title: "Masala nonveg restaurant",
    categories: "Indian",
    rating: "--",
    time: "30 MINS",
    avgPrice: "₹350 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "B12 Garden Restaurant",
    categories: "North Indian",
    rating: "--",
    time: "29 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Cam`s Kitchen",
    categories: "Indian",
    rating: "--",
    time: "30 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "THE CHAWLA'S BAKERY",
    categories: "Bakery, Fast Food, Pizzas, Desserts, Beverages",
    rating: "--",
    time: "24 MINS",
    avgPrice: "₹300 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "Firangi Club",
    categories: "Continental, North Indian",
    rating: "--",
    time: "31 MINS",
    avgPrice: "₹400 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "",
  },
  {
    title: "OM SHREE SAI KRIPA",
    categories: "Chinese, Indian, Juices",
    rating: "--",
    time: "32 MINS",
    avgPrice: "₹200 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Old Bhilwara, Old Bhilwara",
  },
  {
    title: "Tikka N Talk",
    categories: "North Indian",
    rating: "--",
    time: "39 MINS",
    avgPrice: "₹250 FOR TWO",
    image_url: "",
    offer_status: true,
offer : 60,
coupon_code: "STEALDEAL",
price:  200,
delivery_time: 27,
address: "Bhilwara, Bhopal Ganj",
  },
];
